### ISSUE TITLE
Update Node version list

### ISSUE THREAD

**Issue by thebergamo** [OiNutter/node-build#102]
Please update the node version list on install in Mac please.

**Comment by jasonkarns** [comment]
I'm sorry, I don't understand what you're asking. On install, node-build just prints the details of the build.

**Comment by thebergamo** [comment]
When we install node-build, update the Node.js versions after brew complete the installation like a post install script.
Because by default node-build has an outdated list with node versions, I need install node-build-update-defs and update that list for using the latest version of node in Nodenv.

Have a way to update the list on install node-build? Or just installing the plugin?

**Comment by jawshooah** [comment]
> When we install node-build, update the Node.js versions after brew complete the installation like a post install script.

You could create a post-checkout hook in a template dir and do [something like this](https://stackoverflow.com/questions/2141492/git-clone-and-post-checkout-hook/2141577#2141577). But there's nothing @jasonkarns can do to hook into your local git client.

**Comment by jasonkarns** [comment]
Oh, I see; on install of node-build.

The build definitions ship with node-build. So when you install node-build, the latest definitions that it ships with are included.

Assuming you recently installed node-build, the reason your list of available nodes isn't "complete" (with latest nodes like 5.2.0 or 5.3.0) is that you don't have the latest version of node-build. The latest node-build is 2.1.0

It looks like you installed node-build via homebrew. The [latest node-build in homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/node-build.rb#L4) is 2.0.3. There is a [pending PR to homebrew](https://github.com/Homebrew/homebrew/pull/47567) to update to node-build 2.1.0

Your options are to
1. wait for homebrew to update with latest node-build (obviously we have no control over how soon PRs are merged into homebrew)
2. [install node-build as a nodenv plugin](https://github.com/OiNutter/node-build#installing-as-an-nodenv-plugin-recommended) directly via git, so that you can stay up to date without waiting for homebrew
2. [install node-build manually](https://github.com/OiNutter/node-build#installing-as-a-standalone-program-advanced) so that you can stay up to date without waiting for homebrew
3. use the node-build-update-defs plugin to scrape down your own node build definitions without needing to upgrade node-build

If you choose option 2 or 3, you will need to keep node-build up to date yourself, as it would be managed outside of homebrew. To do that, I recommend the [nodenv-update plugin](https://github.com/charlesbjohnson/nodenv-update).

**Comment by thebergamo** [comment]
Thanks very much @jasonkarns... Now, I get the updated list using nodenv's plugin. 
I will wait the homebrew accept the PR for my further installs!

**Comment by jawshooah** [comment]
Yet another alternative: I've just added node-build-update-defs to [homebrew-nodenv-head-only](https://github.com/jawshooah/homebrew-nodenv-head-only). The formula depends on nodenv and node-build, so you could just:

```bash
> brew install --HEAD node-build-update-defs
> nodenv update-version-defs
```

I would echo @jasonkarns though and recommend you just install node-build and node-build-update-defs as nodenv plugins and use nodenv-update to keep them fresh.

**Comment by jasonkarns** [comment]
> I would echo @jasonkarns though and recommend you just install node-build and node-build-update-defs as nodenv plugins and use nodenv-update to keep them fresh.

Agreed. Node has a much faster release cycle than ruby, so the added delay that homebrew adds to the loop is more significant. In fact, that is the exact reason that node-build-update-defs was created ;)

**Comment by thebergamo** [comment]
Interesting!!

Yeah, node releases after the big merge is almost fast than Flash =D

This tips are very helpful!
