### ISSUE TITLE
Help maintaining repo?

### ISSUE THREAD

**Issue by ianks** [OiNutter/node-build#22]
Would you like some help maintaining this project? I would be willing to help test/merge PRs

**Comment by peterkc** [comment]
+1

**Comment by blackjid** [comment]
:+1:

**Comment by jasonkarns** [comment]
potential to create a nodenv org to add additional maintainers to the nodenv suite of repos?

**Comment by OiNutter** [comment]
That sounds sensible and I think it's safe to say given the complete lack of time I've had to look at this stuff in the past few months that it's probably worthwhile. Will take a look into setting something up this weekend and see what the best plan is.

**Comment by OiNutter** [comment]
Important question is who would be interested in helping maintain these repos?

**Comment by jasonkarns** [comment]
I could help

**Comment by ianks** [comment]
I can help maintain this.

**Comment by OiNutter** [comment]
Apparently there already is a nodenv organisation that is serving a fork of wfarr/nodenv so rather than create confusion with that I'm just going to add you guys as collaborators on the repos for now. Tbh I'm not sure if there's much benefit in creating an organisation and trying to move everything across to that. Will see how it goes like this and if it's going to be worth the headache of relocating everything will look into it again.

**Comment by jasonkarns** [comment]
I created a waffle.io board that has https://github.com/OiNutter/nodenv, https://github.com/OiNutter/node-build, https://github.com/OiNutter/nodenv-vars, and https://github.com/jasonkarns/nodenv-each.

I can't add https://github.com/charlesbjohnson/nodenv-update or https://github.com/nicknovitski/nodenv-default-packages because I'm not a contributor on those repos.

The biggest benefit I can see in having an actual org is being able to transition a plugin "into the fold" to immediately grant the team access to the plugin. And automatically make it available as part of the waffle board as well. Manual contributors is fine for now but I still think there is value in an org.

**Comment by jasonkarns** [comment]
Probably should have included the link to the waffle board : https://waffle.io/OiNutter/nodenv

**Comment by zdavis** [comment]
Thanks for keeping this repository alive. My team and I are very happy it exists!

**Comment by jasonkarns** [comment]
@zdavis :green_heart:
